server:
  port: 80

spring:
  application:
    name: cloud-order-service
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  http:
    log-request-details: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fy.springcloud.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #集群
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #单机
      defaultZone: http://eureka7001.com:7001/eureka/