server:
  port: 9002
spring:
  application:
    name: cloud-nacos-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"