server:
  port: 80

spring:
  application:
    name: cloud-order-service
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  http:
    log-request-details: true
  cloud:
    zookeeper:
      connect-string: localhost:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fy.springcloud.entity
