server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: default
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

debug: true