server:
  port: 80

spring:
  application:
    name: cloud-order-service
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  http:
    log-request-details: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fy.springcloud.entity
