server:
  port: 83
spring:
  application:
    name: cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true

service-url:
  nacos-user-service: http://cloud-nacos-server

management:
  endpoints:
    web:
      exposure:
        include: "*"